# See: https://prettier.io/docs/en/configuration

printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
endOfLine: lf
