name: "Checkstyle Reporter"
description: "Reads Checkstyle XML and emits GitHub error/warning annotations"
author: "Craig Motlin"

branding:
  icon: "check-square"
  color: "yellow"

inputs:
  checkstyle_files:
    description: "Glob to locate Checkstyle XML reports (Defaults to **/checkstyle-result.xml)"
    required: false
    default: "**/checkstyle-result.xml"

runs:
  using: node20
  main: dist/index.js
